title: "Dr. Staffan Canback"
description: "My publications and citations"

remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0

url: "https://scanback.github.io"
baseurl: "/docs"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
# SC test
# defaults:
#   - scope:
#       path: ""
#     values:
#       image: https://tellusant.github.io/docs/assets/social-card.png
