title: "TELLUSANT, INC."
description: "Published materials by Tellusant team members"

url: "https://tellusant.github.io"
baseurl: "/docs"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
sitemap:
  path: /docs/sitemap.xml
  # may add later: exclude_from_sitemap:  - /index.html

      
