title: "Dr. Staffan Canback"
description: "Four Decades of Top Management Problem Solving Globally"

# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0

url: "https://scanback.github.io"
baseurl: "/docs"

remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/slate@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

sitemap:
  path: /docs/sitemap.xml

